### ISSUE TITLE
[Bug]: Text color of some elements does not change on going into dark mode

### ISSUE THREAD

**Issue by NutchapolSal** [Quorafind/Obsidian-Memos#339]
### Bug Description

tested on default obsidian skin

some text elements seems to stay dark in dark mode.
from what i've observed:
- tab header text
- "create filter" button
- tag counter
- date picker
  - it is practically invisible until hovered on, that makes it unusable on mobile

### Relevant Screenshot

![image](https://github.com/Quorafind/Obsidian-Memos/assets/17706539/3fb65bdb-19f3-4843-b21f-2bfead4bcd29)
![image](https://github.com/Quorafind/Obsidian-Memos/assets/17706539/00947047-034a-4e73-8b8f-e71c7b77a5be)
![image](https://github.com/Quorafind/Obsidian-Memos/assets/17706539/ce55f343-7c45-4dae-991f-ec39859333a7)

### To Reproduce

1. turn on dark mode
2. view memos page

### Obsidian Version

1.3.7

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by ksdavidc** [comment]
I had the same problem.

I added a css  snippet to make mine better:

```css
.date-picker-wrapper.editor-date-picker {
    background: lightblue;
}

.theme-dark .editor-date-picker > .date-picker-day-container > .date-picker-day-header > .day-item {

color: maroon;
}

.theme-dark .editor-date-picker > .date-picker-day-container > .date-picker-day-header  {
background: maroon;
}

.theme-dark .rta {
background: maroon;
}

.theme-dark .rta  textarea::placeholder {
color: pink;
}

.theme-dark div[data-type='memos_view'] .memo-wrapper > .memo-top-wrapper > .memo-top-left-wrapper > .memo-type-img {
    filter: invert(0.5); 
}
```

**Comment by NutchapolSal** [comment]
i've figured a more general css fix for this (tested with default dark/light theme)
```css
div.workspace-tab-header[data-type="memos_view"] {
    color: var(--tab-text-color);
}
.is-focused div.workspace-tab-header[data-type="memos_view"] {
    color: var(--tab-text-color-focused);
}

div.workspace-leaf-content[data-type="memos_view"] span {
    color: var(--text-normal);
}
```
